repos:
  - repo: https://github.com/GrandGaleTechnologies/behemoth-fastapi
    rev: v7.1.0  
    hooks:
      - id: flake8
        config_file: .flake8

  - repo: https://github.com/GrandGaleTechnologies/behemoth-fastapi
    rev: v3.3.1
    hooks:
      - id: MAIN
        config_file: .pylintrc
        
  - repo: https://github.com/GrandGaleTechnologies/behemoth-fastapi
    rev: v0.7.2
    hooks:
      - id: ruff
        config_file: ruff.toml

